// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: gui.proto

package gui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputKey int32

const (
	InputKey_UP    InputKey = 0
	InputKey_DOWN  InputKey = 1
	InputKey_RIGHT InputKey = 2
	InputKey_LEFT  InputKey = 3
	InputKey_OK    InputKey = 4
	InputKey_BACK  InputKey = 5
)

// Enum value maps for InputKey.
var (
	InputKey_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "RIGHT",
		3: "LEFT",
		4: "OK",
		5: "BACK",
	}
	InputKey_value = map[string]int32{
		"UP":    0,
		"DOWN":  1,
		"RIGHT": 2,
		"LEFT":  3,
		"OK":    4,
		"BACK":  5,
	}
)

func (x InputKey) Enum() *InputKey {
	p := new(InputKey)
	*p = x
	return p
}

func (x InputKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputKey) Descriptor() protoreflect.EnumDescriptor {
	return file_gui_proto_enumTypes[0].Descriptor()
}

func (InputKey) Type() protoreflect.EnumType {
	return &file_gui_proto_enumTypes[0]
}

func (x InputKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputKey.Descriptor instead.
func (InputKey) EnumDescriptor() ([]byte, []int) {
	return file_gui_proto_rawDescGZIP(), []int{0}
}

type InputType int32

const (
	InputType_PRESS   InputType = 0 //*< Press event, emitted after debounce
	InputType_RELEASE InputType = 1 //*< Release event, emitted after debounce
	InputType_SHORT   InputType = 2 //*< Short event, emitted after InputTypeRelease done withing INPUT_LONG_PRESS interval
	InputType_LONG    InputType = 3 //*< Long event, emmited after INPUT_LONG_PRESS interval, asynchronouse to InputTypeRelease
	InputType_REPEAT  InputType = 4 //*< Repeat event, emmited with INPUT_REPEATE_PRESS period after InputTypeLong event
)

// Enum value maps for InputType.
var (
	InputType_name = map[int32]string{
		0: "PRESS",
		1: "RELEASE",
		2: "SHORT",
		3: "LONG",
		4: "REPEAT",
	}
	InputType_value = map[string]int32{
		"PRESS":   0,
		"RELEASE": 1,
		"SHORT":   2,
		"LONG":    3,
		"REPEAT":  4,
	}
)

func (x InputType) Enum() *InputType {
	p := new(InputType)
	*p = x
	return p
}

func (x InputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputType) Descriptor() protoreflect.EnumDescriptor {
	return file_gui_proto_enumTypes[1].Descriptor()
}

func (InputType) Type() protoreflect.EnumType {
	return &file_gui_proto_enumTypes[1]
}

func (x InputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputType.Descriptor instead.
func (InputType) EnumDescriptor() ([]byte, []int) {
	return file_gui_proto_rawDescGZIP(), []int{1}
}

type ScreenFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ScreenFrame) Reset() {
	*x = ScreenFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gui_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreenFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenFrame) ProtoMessage() {}

func (x *ScreenFrame) ProtoReflect() protoreflect.Message {
	mi := &file_gui_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenFrame.ProtoReflect.Descriptor instead.
func (*ScreenFrame) Descriptor() ([]byte, []int) {
	return file_gui_proto_rawDescGZIP(), []int{0}
}

func (x *ScreenFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StartScreenStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartScreenStreamRequest) Reset() {
	*x = StartScreenStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gui_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartScreenStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScreenStreamRequest) ProtoMessage() {}

func (x *StartScreenStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gui_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScreenStreamRequest.ProtoReflect.Descriptor instead.
func (*StartScreenStreamRequest) Descriptor() ([]byte, []int) {
	return file_gui_proto_rawDescGZIP(), []int{1}
}

type StopScreenStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopScreenStreamRequest) Reset() {
	*x = StopScreenStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gui_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopScreenStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopScreenStreamRequest) ProtoMessage() {}

func (x *StopScreenStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gui_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopScreenStreamRequest.ProtoReflect.Descriptor instead.
func (*StopScreenStreamRequest) Descriptor() ([]byte, []int) {
	return file_gui_proto_rawDescGZIP(), []int{2}
}

type SendInputEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  InputKey  `protobuf:"varint,1,opt,name=key,proto3,enum=PB_Gui.InputKey" json:"key,omitempty"`
	Type InputType `protobuf:"varint,2,opt,name=type,proto3,enum=PB_Gui.InputType" json:"type,omitempty"`
}

func (x *SendInputEventRequest) Reset() {
	*x = SendInputEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gui_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendInputEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputEventRequest) ProtoMessage() {}

func (x *SendInputEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gui_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputEventRequest.ProtoReflect.Descriptor instead.
func (*SendInputEventRequest) Descriptor() ([]byte, []int) {
	return file_gui_proto_rawDescGZIP(), []int{3}
}

func (x *SendInputEventRequest) GetKey() InputKey {
	if x != nil {
		return x.Key
	}
	return InputKey_UP
}

func (x *SendInputEventRequest) GetType() InputType {
	if x != nil {
		return x.Type
	}
	return InputType_PRESS
}

type StartVirtualDisplayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartVirtualDisplayRequest) Reset() {
	*x = StartVirtualDisplayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gui_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartVirtualDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVirtualDisplayRequest) ProtoMessage() {}

func (x *StartVirtualDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gui_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVirtualDisplayRequest.ProtoReflect.Descriptor instead.
func (*StartVirtualDisplayRequest) Descriptor() ([]byte, []int) {
	return file_gui_proto_rawDescGZIP(), []int{4}
}

type StopVirtualDisplayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopVirtualDisplayRequest) Reset() {
	*x = StopVirtualDisplayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gui_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopVirtualDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVirtualDisplayRequest) ProtoMessage() {}

func (x *StopVirtualDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gui_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVirtualDisplayRequest.ProtoReflect.Descriptor instead.
func (*StopVirtualDisplayRequest) Descriptor() ([]byte, []int) {
	return file_gui_proto_rawDescGZIP(), []int{5}
}

var File_gui_proto protoreflect.FileDescriptor

var file_gui_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x50, 0x42, 0x5f,
	0x47, 0x75, 0x69, 0x22, 0x21, 0x0a, 0x0b, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x62, 0x0a,
	0x15, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x50, 0x42, 0x5f, 0x47, 0x75, 0x69, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x50, 0x42, 0x5f, 0x47, 0x75,
	0x69, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1b, 0x0a, 0x19, 0x53, 0x74, 0x6f, 0x70, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x44, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2a, 0x43, 0x0a, 0x08,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49,
	0x47, 0x48, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x03, 0x12,
	0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x41, 0x43, 0x4b, 0x10,
	0x05, 0x2a, 0x44, 0x0a, 0x09, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x50, 0x52, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x4c,
	0x45, 0x41, 0x53, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x48, 0x4f, 0x52, 0x54, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x45, 0x50, 0x45, 0x41, 0x54, 0x10, 0x04, 0x42, 0x24, 0x0a, 0x22, 0x63, 0x6f, 0x6d, 0x2e, 0x66,
	0x6c, 0x69, 0x70, 0x70, 0x65, 0x72, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gui_proto_rawDescOnce sync.Once
	file_gui_proto_rawDescData = file_gui_proto_rawDesc
)

func file_gui_proto_rawDescGZIP() []byte {
	file_gui_proto_rawDescOnce.Do(func() {
		file_gui_proto_rawDescData = protoimpl.X.CompressGZIP(file_gui_proto_rawDescData)
	})
	return file_gui_proto_rawDescData
}

var file_gui_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gui_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gui_proto_goTypes = []interface{}{
	(InputKey)(0),                      // 0: PB_Gui.InputKey
	(InputType)(0),                     // 1: PB_Gui.InputType
	(*ScreenFrame)(nil),                // 2: PB_Gui.ScreenFrame
	(*StartScreenStreamRequest)(nil),   // 3: PB_Gui.StartScreenStreamRequest
	(*StopScreenStreamRequest)(nil),    // 4: PB_Gui.StopScreenStreamRequest
	(*SendInputEventRequest)(nil),      // 5: PB_Gui.SendInputEventRequest
	(*StartVirtualDisplayRequest)(nil), // 6: PB_Gui.StartVirtualDisplayRequest
	(*StopVirtualDisplayRequest)(nil),  // 7: PB_Gui.StopVirtualDisplayRequest
}
var file_gui_proto_depIdxs = []int32{
	0, // 0: PB_Gui.SendInputEventRequest.key:type_name -> PB_Gui.InputKey
	1, // 1: PB_Gui.SendInputEventRequest.type:type_name -> PB_Gui.InputType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gui_proto_init() }
func file_gui_proto_init() {
	if File_gui_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gui_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScreenFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gui_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartScreenStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gui_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopScreenStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gui_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendInputEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gui_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartVirtualDisplayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gui_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopVirtualDisplayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gui_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gui_proto_goTypes,
		DependencyIndexes: file_gui_proto_depIdxs,
		EnumInfos:         file_gui_proto_enumTypes,
		MessageInfos:      file_gui_proto_msgTypes,
	}.Build()
	File_gui_proto = out.File
	file_gui_proto_rawDesc = nil
	file_gui_proto_goTypes = nil
	file_gui_proto_depIdxs = nil
}
